image: docker:19.03.1
services:
  - name: docker:19.03.1-dind



variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info


stages:
  - build

build:
  stage: build
  script:
    #- apk add curl
    - docker build . -t blockchain
    - docker run -d -p 5000:5000 --name block blockchain
    - docker inspect block
    #- curl 127.0.0.1:5000/get_chain

